import User from 'src/models/IUser';

export const mockUsers: User[] = [
  {
    id: '1234',
    fullName: 'Jose Moreno',
    age: 26,
    role: 'client_user',
    rut: '26.701.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostics: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: true,
    goals: 'Mejorar condicion fisica y mental',
    markForChange: false,
  },
  {
    id: '1234',
    fullName: 'Jose Moreno',
    age: 26,
    role: 'client_user',
    rut: '26.701.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostics: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: true,
    goals: 'Mejorar condicion fisica y mental',
    markForChange: false,
  },
  {
    id: '234',
    fullName: 'Jose Moreno',
    age: 26,
    role: 'client_user',
    rut: '26.721.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostics: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: false,
    goals: 'Ganar masa muscular',
    markForChange: false,
  },
  {
    id: '124',
    fullName: 'Jose Mijares',
    age: 26,
    role: 'client_user',
    rut: '26.721.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostics: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: false,
    goals: 'Ganar masa muscular',
    markForChange: false,
  },
];
