import User from 'src/models/IUser';

export const mockUsers: User[] = [
  {
    id: '1234',
    fullName: 'Jose Moreno',
    role: 'client_user',
    rut: '26.701.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostic: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: true,
    goal: 'Mejorar condicion fisica y mental',
    markedForChange: false,
  },
  {
    id: '123',
    fullName: 'Jose Moreno',
    role: 'client_user',
    rut: '26.701.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostic: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: true,
    goal: 'Mejorar condicion fisica y mental',
    markedForChange: false,
  },
  {
    id: '234',
    fullName: 'Jose Moreno',
    role: 'client_user',
    rut: '26.721.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostic: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: false,
    goal: 'Ganar masa muscular',
    markedForChange: false,
  },
  {
    id: '124',
    fullName: 'Jose Mijares',
    role: 'client_user',
    rut: '26.721.979-7',
    email: 'josexmoreno1998@gmail.com',
    previousDiagnostic: '',
    phoneNumber: '9 3284 2343',
    yearOfBirth: 1998,
    hasPaid: false,
    goal: 'Ganar masa muscular',
    markedForChange: false,
  },
];
